sudo: true
language: c
compiler:
    #- clang
    - gcc
os:
    - linux

before_install:
    - export ISX_SRC=$PWD
    - sudo apt-get update -qq
    - sudo apt-get install -y dc openmpi-bin libopenmpi-dev
    ## Build libfabric
    - git clone https://github.com/ofiwg/libfabric.git src/libfabric
    - cd src/libfabric
    - ./autogen.sh
    - ./configure --prefix=$HOME/opt/libfabric
    - make -j 4
    - make install
    - export FI_LOG_LEVEL=error
    - cd ../..
    ## Build Hydra
    - cd src
    - wget http://www.mpich.org/static/downloads/3.2/hydra-3.2.tar.gz
    - tar xvzf hydra-3.2.tar.gz
    - cd hydra-3.2/
    - ./configure --prefix=$HOME/opt/hydra
    - make -j 4
    - make install
    - cd ../..
    ## Build Sandia OpenSHMEM
    ## - git clone https://github.com/regrant/sandia-shmem.git src/sandia-shmem
    - git clone https://github.com/Sandia-OpenSHMEM/SOS.git src/sandia-shmem
    - cd src/sandia-shmem
    - ./autogen.sh
    - ./configure --with-ofi=$HOME/opt/libfabric/ --disable-fortran --prefix=$HOME/opt/sandia-shmem-ofi --enable-error-checking --enable-picky --enable-pmi-simple
    - make -j 4
    - make install
    - cd ../..

install:

script:
    - export BASE_PATH=$PATH
    - export BASE_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
    ###
    ### Build and Run ISx (SHMEM)
    ###
    - export PATH=$HOME/opt/sandia-shmem-ofi/bin:$HOME/opt/hydra/bin:$BASE_PATH
    - export LD_LIBRARY_PATH=$HOME/opt/sandia-shmem-ofi/lib:$BASE_LD_LIBRARY_PATH
    - export OSHRUN_LAUNCHER="mpiexec.hydra"
    - export SMA_SYMMETRIC_SIZE='4G'
    - cd $ISX_SRC/SHMEM
    - make CC=oshcc
    - mpiexec.hydra -np 4 ./bin/isx.strong 134217728 output_strong
    - mpiexec.hydra -np 4 ./bin/isx.weak 33554432 output_weak
    - mpiexec.hydra -np 4 ./bin/isx.weak_iso 33554432 output_weak_iso
    - make clean
    - make uint32 CC=oshcc
    - mpiexec.hydra -np 4 ./bin/isx.strong 134217728 output_strong
    - mpiexec.hydra -np 4 ./bin/isx.weak 33554432 output_weak
    - mpiexec.hydra -np 4 ./bin/isx.weak_iso 33554432 output_weak_iso
    - make clean
    - make debug CC=oshcc
    - mpiexec.hydra -np 4 ./bin/isx.strong 16 output_strong
    - mpiexec.hydra -np 4 ./bin/isx.weak 16 output_weak
    - mpiexec.hydra -np 4 ./bin/isx.weak_iso 16 output_weak_iso
    - make clean
    - make optimized CC=oshcc
    - mpiexec.hydra -np 4 ./bin/isx.strong 134217728 output_strong
    - mpiexec.hydra -np 4 ./bin/isx.weak 33554432 output_weak
    - mpiexec.hydra -np 4 ./bin/isx.weak_iso 33554432 output_weak_iso
    - make clean
    - cd ../..
    ###
    ### Build and Run ISx (MPI)
    ###
    - export PATH=$BASE_PATH
    - export LD_LIBRARY_PATH=$BASE_LD_LIBRARY_PATH
    - cd $ISX_SRC/MPI
    - make CC=mpicc.openmpi
    - mpirun.openmpi -np 4 ./bin/isx.strong 134217728 output_strong
    - mpirun.openmpi -np 4 ./bin/isx.weak 33554432 output_weak
    - mpirun.openmpi -np 4 ./bin/isx.weak_iso 33554432 output_weak_iso
    - make clean
    - make optimized CC=mpicc.openmpi 
    - mpirun.openmpi -np 4 ./bin/isx.strong 134217728 output_strong
    - mpirun.openmpi -np 4 ./bin/isx.weak 33554432 output_weak
    - mpirun.openmpi -np 4 ./bin/isx.weak_iso 33554432 output_weak_iso
    - make clean 
    - cd ../..

notifications:
  email:
    recipients:
      - james.dinan@intel.com
      - ulf.r.hanebutte@intel.com
    on_success: [change]
    on_failure: [always] 
